"use client";
import { Inter } from "next/font/google";
import { Sidebar } from "@components/sidebar";

import styles from "./utils.module.css";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
// import "bootstrap/dist/css/bootstrap.min.css";
import { SessionProvider } from "next-auth/react";

// import dynamic from 'next/dynamic';
// import Script from "next/script";

const inter = Inter({ subsets: ["latin"] }); // Font

// export const metadata = {
//   title: "Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const links = [
    { label: "User", path: "/user/login", targetSegment: "user" },
    { label: "Home", path: "/", targetSegment: null },
    { label: "Cluster", path: "/cluster", targetSegment: "cluster" },
    { label: "MQTT", path: "/mqttTests", targetSegment: "mqttTests" },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Sidebar links={links} />
          <div className={`${styles.content}`}>{children}</div>
        </SessionProvider>
      </body>
    </html>
  );
}
